# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class CommentExtraction(BaseModel):
    roles: typing.List["ExtractedRole"]
    is_job_posting: typing.Optional[bool] = None
    extraction_confidence: typing.Optional[typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]] = None

class ExtractedRole(BaseModel):
    role_title: typing.Optional[str] = None
    locations: typing.List[str]
    is_remote: typing.Optional[bool] = None
    remote_regions: typing.List[str]
    employment_type: typing.Optional[types.EmploymentType] = None
    salary_min: typing.Optional[int] = None
    salary_max: typing.Optional[int] = None
    salary_currency: typing.Optional[str] = None
    salary_raw: typing.Optional[str] = None
    equity: typing.Optional[str] = None
    application_method: typing.Optional[str] = None
    company_name: typing.Optional[str] = None
    company_stage: typing.Optional[types.CompanyStage] = None
    company_url: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
