# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CommentExtraction": types.CommentExtraction,
    "stream_types.CommentExtraction": stream_types.CommentExtraction,

    "types.ExtractedRole": types.ExtractedRole,
    "stream_types.ExtractedRole": stream_types.ExtractedRole,


    "types.CompanyStage": types.CompanyStage,

    "types.EmploymentType": types.EmploymentType,

}