# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class CompanyStage(str, Enum):
    PreSeed = "PreSeed"
    Seed = "Seed"
    SeriesA = "SeriesA"
    SeriesB = "SeriesB"
    SeriesC = "SeriesC"
    SeriesDPlus = "SeriesDPlus"
    Public = "Public"
    Bootstrapped = "Bootstrapped"

class EmploymentType(str, Enum):
    FullTime = "FullTime"
    PartTime = "PartTime"
    Contract = "Contract"
    Internship = "Internship"
    Fractional = "Fractional"

# #########################################################################
# Generated classes (2)
# #########################################################################

class CommentExtraction(BaseModel):
    roles: typing.List["ExtractedRole"]
    is_job_posting: bool
    extraction_confidence: typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]

class ExtractedRole(BaseModel):
    role_title: typing.Optional[str] = None
    locations: typing.List[str]
    is_remote: typing.Optional[bool] = None
    remote_regions: typing.List[str]
    employment_type: typing.Optional[EmploymentType] = None
    salary_min: typing.Optional[int] = None
    salary_max: typing.Optional[int] = None
    salary_currency: typing.Optional[str] = None
    salary_raw: typing.Optional[str] = None
    equity: typing.Optional[str] = None
    application_method: typing.Optional[str] = None
    company_name: typing.Optional[str] = None
    company_stage: typing.Optional[CompanyStage] = None
    company_url: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
